import type { Catalogo } from "./store";

/**
 * Catálogo de partida: exactamente lo que había escrito a mano en
 * `src/data/products.ts` antes de que fuese editable desde el panel, con los
 * textos de `messages/*​/products.json` incorporados como campos multiidioma.
 *
 * Se escribe en `data/catalogo.json` la primera vez que alguien lee el
 * catálogo y no se vuelve a mirar. Los ids van fijados a mano (y no generados
 * con `randomUUID`) para que sembrar dos veces —el build de Next arranca
 * varios procesos— no produzca dos catálogos distintos.
 */
export function catalogoInicial(): Catalogo {
  const ahora = "2026-08-01T00:00:00.000Z";
  const base = { creadoAt: ahora, actualizadoAt: ahora };

  return {
    categorias: [
      {
        ...base,
        id: "5c890abe-0be1-4b86-989e-53236031ef51",
        tipo: "vps",
        slug: "vps",
        nombre: { en: "Cloud VPS", es: "Cloud VPS", fr: "Cloud VPS" },
        descripcion: {
          en: "NVMe virtual machines with a 10 Gbps network and DDoS protection included.",
          es: "Máquinas virtuales NVMe con red de 10 Gbps y protección DDoS incluida.",
          fr: "Machines virtuelles NVMe avec réseau 10 Gbps et protection DDoS incluse.",
        },
        etiqueta: { en: "", es: "", fr: "" },
        visible: true,
        orden: 0,
      },
      {
        ...base,
        id: "f3ab0d24-f33f-4935-9e3f-8ebad60b71f5",
        tipo: "dedicados",
        slug: "francia",
        nombre: {
          en: "Dedicated Servers France",
          es: "Servidores Dedicados France",
          fr: "Serveurs Dédiés France",
        },
        descripcion: {
          en: "AMD EPYC and Ryzen bare metal in our Paris datacenter. Guaranteed uplinks and NVMe Gen4, with no overselling.",
          es: "Bare metal AMD EPYC y Ryzen en nuestro datacenter de Paris. Uplinks garantizados y NVMe Gen4, sin overselling.",
          fr: "Bare metal AMD EPYC et Ryzen dans notre datacenter de Paris. Uplinks garantis et NVMe Gen4, sans overselling.",
        },
        etiqueta: {
          en: "🇫🇷 Paris · bare metal",
          es: "🇫🇷 Paris · bare metal",
          fr: "🇫🇷 Paris · bare metal",
        },
        visible: true,
        orden: 1,
      },
      {
        ...base,
        id: "2e0eca44-c1f9-488d-902f-028764845c2b",
        tipo: "dedicados",
        slug: "holanda",
        nombre: {
          en: "Dedicated Servers Netherlands",
          es: "Servidores Dedicados Netherlands",
          fr: "Serveurs Dédiés Netherlands",
        },
        descripcion: {
          en: "AMD EPYC and Ryzen bare metal in Amsterdam with direct peering at AMS-IX. Guaranteed uplinks and NVMe Gen4, with no overselling.",
          es: "Bare metal AMD EPYC y Ryzen en Amsterdam con peering directo en AMS-IX. Uplinks garantizados y NVMe Gen4, sin overselling.",
          fr: "Bare metal AMD EPYC et Ryzen à Amsterdam avec peering direct à l'AMS-IX. Uplinks garantis et NVMe Gen4, sans overselling.",
        },
        etiqueta: {
          en: "🇳🇱 Amsterdam · bare metal",
          es: "🇳🇱 Amsterdam · bare metal",
          fr: "🇳🇱 Amsterdam · bare metal",
        },
        visible: true,
        orden: 2,
      },
    ],

    ubicaciones: [
      {
        ...base,
        id: "bab59e10-cad0-4163-9000-d9822a44550a",
        slug: "francia",
        nombre: { en: "France", es: "France", fr: "France" },
        ciudad: { en: "Paris", es: "Paris", fr: "Paris" },
        nota: {
          en: "< 5 ms to Western Europe",
          es: "< 5 ms a Europa Occidental",
          fr: "< 5 ms vers l'Europe de l'Ouest",
        },
        bandera: "🇫🇷",
        cpu: "",
        provisionLocation: "",
        precioDesde: 8,
        mapX: 42,
        mapY: 54,
        // Oculta hasta que Francia tenga un Proxmox detrás: sin backend, un VPS
        // "en Francia" no puede aprovisionarse solo (ver `provisionLocation`).
        visible: false,
        orden: 0,
      },
      {
        ...base,
        id: "e7c1a4d2-3b6f-4a58-9c0d-2f8b5e91a70c",
        slug: "holanda",
        nombre: { en: "Netherlands", es: "Netherlands", fr: "Netherlands" },
        ciudad: { en: "Amsterdam", es: "Amsterdam", fr: "Amsterdam" },
        nota: {
          en: "< 3 ms to Western Europe · AMS-IX peering",
          es: "< 3 ms a Europa Occidental · peering AMS-IX",
          fr: "< 3 ms vers l'Europe de l'Ouest · peering AMS-IX",
        },
        bandera: "🇳🇱",
        cpu: "Xeon Gold 6150",
        provisionLocation: "nl-ams",
        precioDesde: 8,
        mapX: 46,
        mapY: 44,
        visible: true,
        orden: 1,
      },
    ],

    productos: [
      /* ----------------------------- Cloud VPS ----------------------------- */
      {
        ...base,
        id: "b3a9be28-7689-4b98-9fa9-70b2cbf6feab",
        categoriaId: "5c890abe-0be1-4b86-989e-53236031ef51",
        planId: "vps-start",
        nombre: "VPS Start",
        cpu: "2 vCore AMD EPYC",
        ram: "4 GB DDR5",
        almacenamiento: "60 GB NVMe Gen4",
        red: "10 Gbps · unlimited traffic",
        precio: 8,
        popular: false,
        visible: true,
        orden: 0,
      },
      {
        ...base,
        id: "0cfa8dc3-1196-4d25-8ae7-2613cde83cba",
        categoriaId: "5c890abe-0be1-4b86-989e-53236031ef51",
        planId: "vps-pro",
        nombre: "VPS Pro",
        cpu: "4 vCore AMD EPYC",
        ram: "8 GB DDR5",
        almacenamiento: "120 GB NVMe Gen4",
        red: "10 Gbps · unlimited traffic",
        precio: 14,
        popular: true,
        visible: true,
        orden: 1,
      },
      {
        ...base,
        id: "30bba065-06e8-49b3-8bbf-8eae3b17299e",
        categoriaId: "5c890abe-0be1-4b86-989e-53236031ef51",
        planId: "vps-max",
        nombre: "VPS Max",
        cpu: "8 vCore AMD EPYC",
        ram: "16 GB DDR5",
        almacenamiento: "240 GB NVMe Gen4",
        red: "10 Gbps · unlimited traffic",
        precio: 30,
        popular: false,
        visible: true,
        orden: 2,
      },
      {
        ...base,
        id: "5c0033db-d069-482e-952e-ff1afbcd11b3",
        categoriaId: "5c890abe-0be1-4b86-989e-53236031ef51",
        planId: "vps-scale",
        nombre: "VPS Scale",
        cpu: "16 vCore AMD EPYC",
        ram: "32 GB DDR5",
        almacenamiento: "480 GB NVMe Gen4",
        red: "10 Gbps · unlimited traffic",
        precio: 42,
        popular: false,
        visible: true,
        orden: 3,
      },

      /* -------------------------- Dedicados Francia ------------------------ */
      {
        ...base,
        id: "0207fc88-f8b6-4aa5-b2a0-65f5af6b6848",
        categoriaId: "f3ab0d24-f33f-4935-9e3f-8ebad60b71f5",
        planId: "ded-fr-ryzen-7950x",
        nombre: "Ryzen 7950X",
        cpu: "AMD Ryzen 9 7950X · 16C/32T",
        ram: "64 GB DDR5 ECC",
        almacenamiento: "2 × 1 TB NVMe Gen4",
        red: "1 Gbps guaranteed",
        precio: 150,
        popular: true,
        visible: true,
        orden: 0,
      },
      {
        ...base,
        id: "08f1c283-c447-4485-895d-ae7fdbd56438",
        categoriaId: "f3ab0d24-f33f-4935-9e3f-8ebad60b71f5",
        planId: "ded-fr-epyc-7443",
        nombre: "EPYC 7443",
        cpu: "AMD EPYC 7443 · 24C/48T",
        ram: "128 GB DDR4 ECC",
        almacenamiento: "2 × 1.92 TB NVMe Gen4",
        red: "1 Gbps guaranteed",
        precio: 300,
        popular: false,
        visible: true,
        orden: 1,
      },
      {
        ...base,
        id: "774f54b9-b9df-4f3f-a0a6-440060091206",
        categoriaId: "f3ab0d24-f33f-4935-9e3f-8ebad60b71f5",
        planId: "ded-fr-epyc-9354",
        nombre: "EPYC 9354",
        cpu: "AMD EPYC 9354 · 32C/64T",
        ram: "256 GB DDR5 ECC",
        almacenamiento: "4 × 3.84 TB NVMe Gen4",
        red: "10 Gbps dedicated",
        precio: 500,
        popular: false,
        visible: true,
        orden: 2,
      },
      {
        ...base,
        id: "f24cbd44-b300-44d5-87dd-bbf8288af8db",
        categoriaId: "f3ab0d24-f33f-4935-9e3f-8ebad60b71f5",
        planId: "ded-fr-dual-epyc-9454",
        nombre: "Dual EPYC 9454",
        cpu: "2 × AMD EPYC 9454 · 96C/192T",
        ram: "512 GB DDR5 ECC",
        almacenamiento: "6 × 3.84 TB NVMe Gen4",
        red: "10 Gbps dedicated",
        precio: 900,
        popular: false,
        visible: true,
        orden: 3,
      },
      {
        ...base,
        id: "d9132059-bf26-4151-b59d-c4f7bd5064eb",
        categoriaId: "f3ab0d24-f33f-4935-9e3f-8ebad60b71f5",
        planId: "ded-fr-storage-360",
        nombre: "Storage 360",
        cpu: "AMD EPYC 7443 · 24C/48T",
        ram: "128 GB DDR4 ECC",
        almacenamiento: "18 × 20 TB HDD + 2 TB NVMe cache",
        red: "2 Gbps guaranteed",
        precio: 1700,
        popular: false,
        visible: true,
        orden: 4,
      },

      /* -------------------------- Dedicados Holanda ------------------------ */
      {
        ...base,
        id: "caee7162-3de2-45d3-8a85-10d78c2ed896",
        categoriaId: "2e0eca44-c1f9-488d-902f-028764845c2b",
        planId: "ded-nl-ryzen-7950x",
        nombre: "Ryzen 7950X",
        cpu: "AMD Ryzen 9 7950X · 16C/32T",
        ram: "64 GB DDR5 ECC",
        almacenamiento: "2 × 1 TB NVMe Gen4",
        red: "1 Gbps guaranteed",
        precio: 150,
        popular: true,
        visible: true,
        orden: 0,
      },
      {
        ...base,
        id: "2fc8d8d5-b896-4dd3-b2bf-6ba771f29335",
        categoriaId: "2e0eca44-c1f9-488d-902f-028764845c2b",
        planId: "ded-nl-epyc-7443",
        nombre: "EPYC 7443",
        cpu: "AMD EPYC 7443 · 24C/48T",
        ram: "128 GB DDR4 ECC",
        almacenamiento: "2 × 1.92 TB NVMe Gen4",
        red: "1 Gbps guaranteed",
        precio: 300,
        popular: false,
        visible: true,
        orden: 1,
      },
      {
        ...base,
        id: "cec09aab-f063-477c-a3d4-2219c02ef6bf",
        categoriaId: "2e0eca44-c1f9-488d-902f-028764845c2b",
        planId: "ded-nl-epyc-9354",
        nombre: "EPYC 9354",
        cpu: "AMD EPYC 9354 · 32C/64T",
        ram: "256 GB DDR5 ECC",
        almacenamiento: "4 × 3.84 TB NVMe Gen4",
        red: "10 Gbps dedicated",
        precio: 500,
        popular: false,
        visible: true,
        orden: 2,
      },
      {
        ...base,
        id: "dd02ab64-2327-4f7b-9e4a-6c595a3cd490",
        categoriaId: "2e0eca44-c1f9-488d-902f-028764845c2b",
        planId: "ded-nl-dual-epyc-9454",
        nombre: "Dual EPYC 9454",
        cpu: "2 × AMD EPYC 9454 · 96C/192T",
        ram: "512 GB DDR5 ECC",
        almacenamiento: "6 × 3.84 TB NVMe Gen4",
        red: "10 Gbps dedicated",
        precio: 900,
        popular: false,
        visible: true,
        orden: 3,
      },
      {
        ...base,
        id: "5c0b4349-aa5c-4d4a-ad2f-d67bb9b0a8d2",
        categoriaId: "2e0eca44-c1f9-488d-902f-028764845c2b",
        planId: "ded-nl-storage-360",
        nombre: "Storage 360",
        cpu: "AMD EPYC 7443 · 24C/48T",
        ram: "128 GB DDR4 ECC",
        almacenamiento: "18 × 20 TB HDD + 2 TB NVMe cache",
        red: "2 Gbps guaranteed",
        precio: 1700,
        popular: false,
        visible: true,
        orden: 4,
      },
    ],
  };
}
